### ISSUE TITLE
rete-cli won't compile context-menu-plugin

### ISSUE THREAD

**Issue by Claybarn** [retejs/context-menu-plugin#82]
The rete-cli won't compile this plugin, emitting a "Type generating failed" error. However, it does work on other plugins and the "master" branch. 

Minimal steps to reproduce:

`git clone https://github.com/retejs/context-menu-plugin`
`cd context-menu-plugin`
`npm i -g rete-cli`
`rete build --config rete.config.ts`

However, this works:

`git checkout master`
`rete build --config rete.config.ts`

and this works:

`git clone https://github.com/retejs/rete-kit`
`cd rete-kit`
`rete build --config rete.config.ts`

**Comment by Ni55aN** [comment]
All plugin's dependencies should be installed:

```bash
git clone https://github.com/retejs/context-menu-plugin
cd context-menu-plugin
npm ci
npm run build
```

btw, `master` branch is for Rete.js v1

**Comment by Claybarn** [comment]
Ah yes that worked for me. Perhaps the documentation for rete-cli on the [website](https://retejs.org/docs/development/rete-cli) should be updated?

**Comment by Ni55aN** [comment]
[Building the project](https://retejs.org/docs/development/rete-cli#build-rete-cli) doesn't require installing dependencies, since in that example there are no dependencies. Since you forked an existing package that already has dependencies, you need to install them.

I guess it should be mentioned in [Code contribution](https://retejs.org/docs/contribution#code)
